---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: plex
spec:
  chartRef:
    kind: OCIRepository
    name: plex
  interval: 1h
  values:
    controllers:
      plex:
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          app:
            image:
              repository: ghcr.io/home-operations/plex
              tag: 1.43.4.10903@sha256:fdc6fe82bc7d8acd08fc0aa581fcb76722803ba5905e2537135a697347dd6149
            env:
              TZ: Europe/Paris
              PLEX_ADVERTISE_URL: https://plex.timcasa.me:443,http://192.168.1.210:32400,http://plex.media.svc.cluster.local:32400
              PLEX_NO_AUTH_NETWORKS: 192.168.1.0/24
            probes:
              liveness:
                enabled: true
                spec:
                  periodSeconds: 30
                  timeoutSeconds: 5
                  failureThreshold: 5
              readiness:
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /identity
                    port: &port 32400
                  periodSeconds: 10
                  timeoutSeconds: 5
                  failureThreshold: 5
              startup:
                enabled: true
                spec:
                  failureThreshold: 30
                  periodSeconds: 10
            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: true
              capabilities: { drop: [ "ALL" ] }
            resources:
              requests:
                cpu: 100m
                memory: 2Gi
              limits:
                cpu: "4"
                memory: 5Gi
    defaultPodOptions:
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
        fsGroupChangePolicy: OnRootMismatch
    service:
      app:
        type: LoadBalancer
        annotations:
          lbipam.cilium.io/ips: 192.168.1.210
        externalTrafficPolicy: Cluster
        ports:
          http:
            port: *port
    route:
      app:
        annotations:
          gatus.home-operations.com/endpoint: |-
            conditions: ["[STATUS] == 401"]
        hostnames:
        - "{{ .Release.Name }}.timcasa.me"
        parentRefs:
        - name: envoy-internal
          namespace: network
    persistence:
      config:
        existingClaim: "{{ .Release.Name }}"
      media:
        type: nfs
        server: 192.168.1.17
        path: /mnt/oasis/Media
        globalMounts:
        - path: /media
          readOnly: true
      tmp:
        type: emptyDir
      transcode:
        type: emptyDir
        globalMounts:
        - path: /transcode
