---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: airflow
spec:
  interval: 1h
  chart:
    spec:
      chart: airflow
      version: "1.22.0"
      sourceRef:
        kind: HelmRepository
        name: apache-airflow
  valuesFrom:
  - kind: Secret
    name: airflow-secret
    valuesKey: admin-password
    targetPath: webserver.defaultUser.password
  install:
    remediation:
      retries: -1
  values:
    executor: KubernetesExecutor
    fernetKeySecretName: airflow-secret
    webserverSecretKeySecretName: airflow-secret
    migrateDatabaseJob:
      useHelmHooks: false
    createUserJob:
      useHelmHooks: false
    webserver:
      defaultUser:
        enabled: true
        username: admin
        email: admin@timcasa.me
        firstName: Admin
        lastName: User
      replicas: 1
      resources:
        requests:
          cpu: 50m
          memory: 512Mi
        limits:
          memory: 1Gi
    scheduler:
      replicas: 1
      resources:
        requests:
          cpu: 50m
          memory: 212Mi
        limits:
          memory: 1Gi
    triggerer:
      replicas: 1
      persistence:
        enabled: false
      resources:
        requests:
          cpu: 10m
          memory: 156Mi
        limits:
          memory: 1Gi
    postgresql:
      enabled: false
    data:
      metadataSecretName: airflow-metadata-secret
    redis:
      enabled: false
    statsd:
      enabled: false
    flower:
      enabled: false
    workers:
      replicas: 0
    logs:
      persistence:
        enabled: false
    dags:
      persistence:
        enabled: true
        storageClassName: openebs-hostpath
        size: 1Gi
      gitSync:
        enabled: false
