---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: filebrowser
spec:
  chartRef:
    kind: OCIRepository
    name: filebrowser
  interval: 1h
  values:
    controllers:
      filebrowser:
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          app:
            image:
              repository: filebrowser/filebrowser
              tag: v2.63.23@sha256:a469ea076d4a1b4b1d86a41d130f2f536cd9da996a2b1fb39c0d7635f9d89b9a
            env:
              TZ: Europe/Paris
              FB_DATABASE: /config/filebrowser.db
              FB_ROOT: /data
              FB_LOG: stdout
            envFrom:
            - secretRef:
                name: filebrowser-secret
            probes:
              liveness: &probes
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /health
                    port: &port 80
                  periodSeconds: 10
                  timeoutSeconds: 1
                  failureThreshold: 3
              readiness: *probes
              startup:
                enabled: false
            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: true
              capabilities: { drop: [ "ALL" ] }
            resources:
              requests:
                cpu: 10m
              limits:
                memory: 512Mi
        pod:
          securityContext:
            runAsUser: 1000
            runAsGroup: 1000
            runAsNonRoot: true
            fsGroup: 1000
            fsGroupChangePolicy: OnRootMismatch
    service:
      app:
        type: LoadBalancer
        annotations:
          lbipam.cilium.io/ips: 192.168.1.219
        externalTrafficPolicy: Cluster
        controller: filebrowser
        ports:
          http:
            port: *port
    route:
      app:
        hostnames:
        - filebrowser.timcasa.me
        parentRefs:
        - name: envoy-internal
          namespace: network
    persistence:
      config:
        existingClaim: filebrowser
      media:
        type: nfs
        server: 192.168.1.17
        path: /mnt/oasis/Media
        globalMounts:
        - path: /data/Media
      backups:
        type: nfs
        server: 192.168.1.17
        path: /mnt/oasis/Backups
        globalMounts:
        - path: /data/Backups
      appdata:
        type: nfs
        server: 192.168.1.17
        path: /mnt/oasis/Appdata
        globalMounts:
        - path: /data/Appdata
      tmp:
        type: emptyDir
